version: "3.7"
services:
  node:
    build:
      context: ../.
      dockerfile: docker/DEV.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules